### ISSUE TITLE
Static method cannot be named "getInstance"

### ISSUE THREAD

**Issue by davidbeckingsale** [LLNL/shroud#34]
We have a static method `getInstance`, used to access a singleton class in Umpire: https://github.com/LLNL/Umpire/blob/develop/src/umpire/ResourceManager.hpp#L41

When describing this in the shroud yaml file as:

```
- decl: class ResourceManager
  declarations:
     - decl: static ResourceManager& getInstance()
```

we hit the following problem:

`There is already a procedure with binding name 'get_instance' for the derived type 'umpire_resourcemanager'`

**Comment by ltaylor16** [comment]
Shroud automatically creates a getter and setter method for the C++ object which is shadowed by the derived type.  The default names are 'get_instance' and 'set_instance'.  The  C++ name `getInstance` is changed to `get_instance` for Fortran by default (since Fortran is not case sensitive).  The name conflicts and the compiler complains.  The easiest work around is to suppress the creation of the getter and setter by setting their names to blank use a format block on the class:

    - decl: class ResourceManager
      format:
         F_name_instance_get:
         F_name_instance_set:

You can also explicitly name them something else if you want to keep them.  The other option is to change the name of the Fortran wrapper for `getInstance` to something else using a format block on the method:

    - decl: static ResourceManager& getInstance()
      format:
        F_name_impl: non_conflicting_name

**Comment by davidbeckingsale** [comment]
Thanks! Are there any side effects from disabling the getter/setters?

**Comment by ltaylor16** [comment]
Not really.  A typical user should not need access to the raw C++ pointer.

**Comment by davidbeckingsale** [comment]
Perfect, I will give that try. I think I tried using `F_name_impl` before and something was still amiss, but maybe it did work.

In any case, it's nice to able to have the names match across C++/C/Fortran. Thanks again.

**Comment by davidbeckingsale** [comment]
Suppressing the getter/setter creation worked, closing.
